### ISSUE TITLE
Which is best?

### ISSUE THREAD

**Issue by madmaniak** [smallnest/C1000K-Servers#1]
Do you have any benchmarks for these implementations?

**Comment by smallnest** [comment]
Yes. I have done some tests and wrote a post in Chinese: http://colobu.com/2015/07/14/performance-comparison-of-7-websocket-frameworks/

Netty is the best.

Go, Node.js, Undertow, vert.x is also good.
Jetty, Grizzly and Spray can't set up 1 million connections.

**Comment by madmaniak** [comment]
Cool! Thanks for the answer - I can't read Chinese yet. Did you see https://github.com/uWebSockets/uWebSockets and what do you think about it?

**Comment by smallnest** [comment]
an interesting project. I will try to add it in this project if it has high performance. Thanks.
