### ISSUE TITLE
Could you please add more detailed document?

### ISSUE THREAD

**Issue by kenshinji** [smallnest/C1000K-Servers#3]
Hi there, I came across you [blog post](http://colobu.com/2015/05/22/implement-C1000K-servers-by-spray-netty-undertow-and-node-js/) a couple days ago, it's fantastic, thankfully you also offer your code here. We are currently looking for a solution of supporting 100k websockets concurrent connections, you code is obviously a huge help to us. However I found the README.md here is too simple to read. I'd really appreciate it if you can offer more details on how to run the performance test you mentioned in your blog post with your code here. That would be great, thanks :)

**Comment by wuqunfei** [comment]
Me too, sbt/scala tool is not familiar with everyone. How can I build the server and start it, the question is also for client.

**Comment by smallnest** [comment]
you should install the sbt tool: http://www.scala-sbt.org/.

Then run  "sbt clean dist".

**Comment by kenshinji** [comment]
yes, basically the project code is good, what it is lack of is a detailed document, which should include how to install, how to run test, etc.

**Comment by smallnest** [comment]
I reopen it so I can monitor whether other readers have the same issues.
This project is written by Scala and sbt, so you need to install sbt and scala first.

I have a doc to introduce how to compile, deploy and config server and clients.
For scala projects, they are packaged into one zipped file. Unzip the file and you will the execution script and the conf file.
For go project, it is compile to one executable file and its conf file is conf.json. You can run it directly.

Hope those could help you.

If you have any issues, please add comments in this issue or open a new issue.

**Comment by wuqunfei** [comment]
cd /Applications/C1000K-Servers/netty
[wuqunfei@localhost netty]$ sbt dist
[info] Set current project to netty (in build file:/home/wuqunfei/Applications/C1000K-Servers/netty/)
[error] Not a valid command: dist (similar: set, iflast, last)
[error] Not a valid key: dist (similar: test, ivy-sbt, history)
[error] dist
[error]

**Comment by wuqunfei** [comment]
Sorry I checkout your repo, and cd netty folder, then run stb dist.
But it is not work...

Thanks for your support

**Comment by smallnest** [comment]
you should run in parent directory, not netty dir

**Comment by wuqunfei** [comment]
sorry, it works. I am not good at sbt tools
