### ISSUE TITLE
virtual network interface is not working on Amazon cloud 

### ISSUE THREAD

**Issue by wuqunfei** [smallnest/C1000K-Servers#4]
I add virtual network interface on amazon EC2, it does not work. Do you know why?

for example:
my intranet IP is like 172.31.7.55, then I add like this 
ifconfig eth0:1 172.31.7.60 netmask 255.255.240.0 down

I use ifconfig command, I saw it on the list, do you have some experience about this?

**Comment by smallnest** [comment]
I think it is aws limit or aws issue

**Comment by wuqunfei** [comment]
so sad, but anyway thanks. You test case is so nice. I am using it and expend it on EC2, I will release it after some days.

**Comment by smallnest** [comment]
I remember aws can set multiple private ip address on their web GUI. you can google it.
