### ISSUE TITLE
go版本实现存在问题

### ISSUE THREAD

**Issue by mengskysama** [smallnest/C1000K-Servers#6]
WriteMessage重入会导致picnic，使用goroutine + channel经过修改后性能下降严重。

```
func wsDispath(ws *websocket.Conn, ch chan string) {
        defer func() {
        }()
        for {
                data := <-ch
                err := ws.WriteMessage(websocket.TextMessage, []byte(data))
                if err != nil {
                        fmt.Println("Error: " + err.Error())
                        return
                }
        }
}
```

**Comment by smallnest** [comment]
go-httpfast

**Comment by smallnest** [comment]
There are two golang implementation and I guess you mean go-fasthttp.

go-fasthttp uses github.com/fasthttp-contrib/websocket and  it is fork of https://github.com/gorilla/websocket .

gorilla/websocket connections are not **thead-safe**. It means you must not 

>  Connections support one concurrent reader and one concurrent writer.
> Applications are responsible for ensuring that no more than one goroutine calls the write methods  (NextWriter, SetWriteDeadline, WriteMessage, WriteJSON) concurrently and that no more than one goroutine calls the read methods (NextReader, SetReadDeadline, ReadMessage, ReadJSON, SetPongHandler, SetPingHandler) concurrently. 

For performance, you can share your test code and submit issues to gorilla/websocket.

In this project  codes of go-fasthttp is different with your test case.
